---
title: "visualize climate functions"
date: "April 17, 2019"
---

```{r setup}
# For R projects
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Purpose
Script to visualize the moisture and temperature climate functions. The intent is to show the point of neutral change where the functions output a value of 1. 

# Load libraries

```{r}
library(ggplot2)
library(patchwork)
```

# Define climate functions

From Adair et al. 2008
```{r}
# From Adair
FW_Adair <- function(PPT ,PET) {
 return(1/(1 + 30 * exp((-8.5 * (PPT/PET)))))
}
FT_Adair <- function(Temp) {
return(exp(308.56 * ((1/56.02)-(1/((273.15 + Temp)-227.13)))))
}
```

Create the temperature function visualization

```{r}
# set temp values in celcius
temps <- seq(0, 30, 1)

# create dataframe of temps and ft() values
temps <- data.frame("temp" = temps,
                    "temp_factor" = FT_Adair(temps))

# create plot object
ft <-
  ggplot(temps, aes(x = temp, y = temp_factor)) +
  theme_test() +
  geom_line(size = 2, col = "royalblue2") +
  geom_point(x = 10,
             y = 1,
             color = "red",
             size = 3) +
  annotate("text",
           x = 18,
           y = 1,
           label = "Point of Neutral Change",
           size = 5) +
  labs(x = "Temperature (C)",
       y = "Decomposition Factor",
       title = "Temperature Function") +
  theme(text = element_text(size = 20))
```

Create moisture function visualization

```{r}
# unitless moisture values
Moist_fact <- seq(.1,2,.1)

# df of moisture values and function outputs
moist_df <- data.frame("moisture_level" = seq(.1,2,.1),
           "moisture_factor" = (1/(1 + 30 * exp((-8.5 * (Moist_fact))))))

# create plot object
fm <-
  ggplot(moist_df, aes(x = moisture_level, y = moisture_factor)) +
  theme_test() +
  geom_line(size = 2, col = "royalblue2") +
  geom_point(x = 1,
             y = .998,
             color = "red",
             size = 3) +
  annotate("text",
           x = 1.3,
           y = .95,
           label = "Point of Neutral Change",
           size = 5) +
  labs(x = "Ratio of PPT / PET ",
       y = "Decomposition Factor",
       title = "Moisture Function") +
  theme(text = element_text(size = 20))
```

## Arrange plots together

```{r}
ft + fm
```

Output plot
```{r}
ggsave(plot = last_plot(),
       filename = "images/neutral_climate.png",
       height = 7,
       width = 11,
       dpi = 400)
```


